development:
  log_level: 'DEBUG'
  hyperloglog_precision: 10
  app_redis_url: 'redis://localhost:6379/0'
  unlink_app_redis: true
  resque_redis_url: 'redis://localhost:6379/1'

production:
  log_level: 'WARN'
  hyperloglog_precision: 10
  app_redis_url: 'redis://localhost:6380'
  resque_redis_url: 'redis://localhost:6381'

staging:
  log_level: 'DEBUG'
  hyperloglog_precision: 10

test:
  log_level: 'WARN'
  hyperloglog_precision: 10
  app_redis_url: 'redis://localhost:6379/14'
  resque_redis_url: 'redis://localhost:6379/15'
